name: gyde_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.5.0'
dependencies:
  gap: ^3.0.1
  intl: ^0.18.0
  file_picker: ^8.1.2
  equatable: ^2.0.5
  flutter: null
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  logger: ^1.4.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.6
  flutter_slidable: ^0.6.0
  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.16
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.5
  calendar_date_picker2: ^0.3.1
  animated_text_kit: ^4.2.2
  form_validator: ^1.0.0
  get_it: ^7.2.0
  connectivity_plus: ^2.3.1
  flutter_secure_storage: ^6.0.1
  lottie: ^1.3.0
dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  stacked_generator: ^1.3.3
  very_good_analysis: ^6.0.0
flutter:
  uses-material-design: true
  generate: true
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/steve.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/steve.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: assets/images/steve.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/steve.png
