name: gyde_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'
dependencies:
  gap: ^2.0.0
  intl: ^0.19.0
  file_picker: ^8.1.2
  equatable: ^2.0.5
  flutter: ^3.7.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  logger: ^1.4.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0
  google_sign_in: ^6.1.0
  apple_sign_in: ^0.1.0
  provider: ^6.1.0
  http: ^0.15.0
  flutter_form_builder: ^7.0.0
  flutter_datetime_picker: ^1.5.0
dev_dependencies:
  build_runner: ^2.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  stacked_generator: ^1.3.3
  very_good_analysis: ^6.0.0
flutter:
  uses-material-design: true
  generate: true
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/steve.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/steve.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: assets/images/steve.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/steve.png
