name: gyde_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0 <4.0.0'
dependencies:
  gap: ^2.0.0
  intl: ^0.18.0
  file_picker: ^8.1.2
  equatable: ^2.0.5
  flutter: null
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  logger: ^1.4.0
  flutter_localizations: null
  url_launcher: ^6.1.10
  firebase_core: ^2.10.0
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.0
  provider: ^6.1.5
  shared_preferences: ^2.1.0
  connectivity_plus: ^4.0.1
  calendar_date_picker2: ^0.4.0
  http: ^1.1.0
  secure_storage: ^5.1.0
  flutter_staggered_grid_view: ^0.5.0
  modal_progress_hud_nsn: ^1.0.0
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test: null
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  stacked_generator: ^1.3.3
  very_good_analysis: ^6.0.0
  mockito: ^5.4.0
flutter:
  uses-material-design: true
  generate: true
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/steve.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/steve.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: assets/images/steve.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/steve.png
